# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Installing Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      # Runs a set of commands using the runners shell
      - name: GitHub for Yarn Start
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
                    
      # Runs a set of commands using the runners shell
      - name: Installing Yarn
        run: npm install -g yarn
      
      # Runs a set of commands using the runners shell
      - name: Build Yarn
        run: yarn build
      
      # Runs a set of commands using the runners shell
      - name: Installing Surge
        run: npm install -g surge

      # Runs a set of commands using the runners shell
      - name: Deployin on Surge
        run: surge ./build http://bc_2020_cls13b.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
